#variables:
 # MAVEN_CLI_OPTS: "clean"
  #EXECUTABLE_POM_FILE_PATH: "project_Test"

stages:
    - build
    - test
    - deployTest
    - deployProd
    
build:
  stage: build
  image: maven:3.6.3-jdk-11
  before_script:
    - cd Group2
  script:
    - mvn install
  tags:
    - dalfcs_gitlab_docker_ci

test:
  stage: test
  image: maven:3.6.3-jdk-11
  before_script:
    - cd Group2
  script:
    - mvn test
  tags:
   - dalfcs_gitlab_docker_ci
   
deployeTest:
  stage: deployTest
  image: ruby:latest
  before_script:
    - cd Group2
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME_TEST --api-key=$HEROKU_API_KEY_TEST
  environment:
    name: staging
    url: $HEROKU_TEST_URL
  tags:
    - dalfcs_gitlab_docker_ci
  only:
    - development

deployProd:
  stage: deployProd
  image: ruby:latest
  before_script:
    - cd Group2
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME_TEST --api-key=$HEROKU_API_KEY_TEST
  environment:
    name: staging
    url: $HEROKU_PROD_URL
  tags:
    - dalfcs_gitlab_docker_ci
  only:
    - master
