# This YAML file demonstrates building a gradle console app and deploying it to your
# Timberlea account via secure copy.

# NOTE: It does not upload your test results to GitLab, you will need
# to figure that out still.


#before_script:
  # The following line is only necessary if using a docker-based runner.
  #- apk add --no-cache openssh-client
 # - chmod +x ./gradlew
 
variables:
  EXECUTABLE_TO_DEPLOY: "app/build/outputs/apk/debug/app-debug.jar"
  DESTINATION_FILE: "App-${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}.apk" 
 

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - mvn -f Group2/ clean compile
  artifacts:
    paths:
    - app/build/outputs/
  tags:
    - ugrad


test:
  stage: test
  script:
    - mvn -f Group2/ clean verify
  artifacts:
    when: always
    reports:
      junit:
        - Group2/target/surefire-reports/TEST-*.xml
  tags:
    - ugrad

deploy:
  stage: deploy
  tags:
    - ugrad
  artifacts:
    paths:
      - app/build/outputs
  script:
    - chmod og-rwx ${DEPLOY_SSH_KEY}
    - scp -r -o StrictHostKeyChecking=no -i "${DEPLOY_SSH_KEY}" ${EXECUTABLE_TO_DEPLOY} "${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}/${DESTINATION_FILE}"