package employeePerformance.abstractFactory;

import employeePerformance.Interfaces.IBarChartGeneration;
import employeePerformance.Interfaces.IEmployeeEfficiencyCalculator;
import employeePerformance.Interfaces.IEmployeePerformanceDB;
import employeePerformance.Interfaces.IEmployeeProductivityCalculator;
import employeePerformance.Interfaces.IFetchedPerformanceDetails;
import employeePerformance.Interfaces.IGenerateEmployeePerformanceReport;
import employeePerformance.Interfaces.IInputEmployeeDetails;
import userinterface.IInputOutputHandler;

public interface IEmployeePerformanceFactory 
{
	public IInputEmployeeDetails userInput(String date, String employeeId);
	public IGenerateEmployeePerformanceReport getPerformanceReport (IInputOutputHandler inputOutputHandler); 
	public IEmployeePerformanceDB employeedetailsDB ( IInputEmployeeDetails inputEmployeeDetails, IFetchedPerformanceDetails fetchedPerformanceDetails, IInputOutputHandler inputOutputHandler); 
	public IEmployeeEfficiencyCalculator getEmployeeEfficiencyCalculator(IInputOutputHandler inputOutputHandler); 
	public IFetchedPerformanceDetails fetchedPerformanceDetails(String ticketLevel, String count, String startDate, String expectedEndDate, String endDate, double workingHours);
	public IEmployeeProductivityCalculator getEmployeeProductivityCalculator(IInputOutputHandler inputOutputHandler);
	public IBarChartGeneration getbarchartGeneration(IInputOutputHandler inputOutputHandler);
}
